EXTENDS:
    - "https://raw.githubusercontent.com/llaville/.github/refs/heads/master/.mega-linter-base.yml"
ENABLE:
    - ACTION
    - EDITORCONFIG
    - MARKDOWN
    - PHP
    - YAML
DISABLE_LINTERS:
    - MARKDOWN_MARKDOWN_TABLE_FORMATTER
    - MARKDOWN_MARKDOWN_LINK_CHECK
    - PHP_BUILTIN
    - PHP_PHPCSFIXER
    - PHP_PSALM
    - YAML_V8R
PRINT_ALL_FILES: false
