---
site_name: Graph-UML
site_url: https://llaville.github.io/graph-uml
repo_url: https://github.com/llaville/graph-uml # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository
site_author: Laurent Laville
edit_uri: "" # hide edit button -- https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#edit-button
theme:
    name: material
    palette: # Color palette toggle -- https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
        # editorconfig-checker-disable
        - scheme: default
          primary: red
          toggle:
              icon: material/lightbulb-outline
              name: Switch to dark mode
        - scheme: slate
          toggle:
              icon: material/lightbulb
              name: Switch to light mode
        # editorconfig-checker-enable
    features:
        - navigation.instant # Instant loading -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
        - navigation.tabs # Navigation tabs -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
        - navigation.indexes # Section index pages -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
        - navigation.top # Back-To-Top button -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
markdown_extensions:
    - pymdownx.highlight # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
    - pymdownx.superfences # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences
nav:
    - "Home": index.md
    - "Getting-Started": getting-started.md
    - "Features":
          - "Formatters": 01_Features/Formatters.md
          - "Generators": 01_Features/Generators.md
          - "Options": 01_Features/Options.md
    - "Cookbook":
          - "Class diagrams":
                - "Single Class": 02_Cookbook/Single_Class.md
                - "Multiple Classes": 02_Cookbook/Multiple_Classes.md
                - "Without Elements": 02_Cookbook/Without_Elements.md
          - "Extension diagram": 02_Cookbook/Php_Extensions.md
