---
name: GitHub-Pages

on:
    push:
        branches:
            - master
            - "1.6"
        paths:
            - docs/**
    pull_request:
    workflow_dispatch:

jobs:
    deploy:
        uses: llaville/.github/.github/workflows/gh-pages.yml@master
        with:
            destination-dir: "1.6"
            hook-script: "resources/gh-pages-hook.sh"
            force-orphan: false
            php-extensions: "lzf"  # required to write assets of example/php-extensions/
