---
name: Unit Tests

on:
    push:
        paths-ignore:
            - 'docs/**'
    pull_request:
        branches:
            - master
            - "1.4"
        paths-ignore:
            - 'docs/**'
    workflow_call:

jobs:
    lint_files:
        uses: llaville/.github/.github/workflows/mega-linter.yml@master
        with:
            repository: ${{ github.repository }}
            php-version: "8.0"

    unit_tests:
        needs: lint_files

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    -
                        os: ubuntu-latest
                        php: 8.0
                        tools: phpunit:9.6
                    -
                        os: ubuntu-latest
                        php: 8.1
                        tools: phpunit:10.5

        name: UML Graphs

        steps:
            -   # https://github.com/actions/checkout
                name: Checkout
                uses: actions/checkout@v4

            -   # https://github.com/shivammathur/setup-php
                name: Setup PHP runtime
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: "none"
                    tools: ${{ matrix.tools }}

            -   # https://github.com/ramsey/composer-install
                name: Install Composer dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: "--prefer-dist"

            -   # https://github.com/sebastianbergmann/phpunit/tree/9.6
                name: Unit tests with PHPUnit 9
                if: ${{ matrix.php == '8.0' }}
                run: phpunit --configuration ./phpunit-9.xml --testdox --do-not-cache-result
            -   # https://github.com/sebastianbergmann/phpunit/tree/10.5
                name: Unit tests with PHPUnit 10
                if: ${{ matrix.php != '8.0' }}
                run: phpunit --testdox --do-not-cache-result --no-progress
